"use client";

import { useState } from "react";
import Link from "next/link";
import { AlertCircle, ArrowRight, CalendarClock, CheckSquare, FileText, ListTodo, Sparkles, Upload } from "lucide-react";
import { documents, getDaysRemaining, getRequirementStats, getTaskStats, mockToday, openTasks, primaryDocument, upcomingDeadlines, type PaperTask } from "@/lib/mock-data";
import { DeadlineRow, DocumentRow, MetricCard, PrimaryButton, SectionTitle, StatusBadge, TaskStatusIcon } from "./ui";

export function Dashboard() {
  const [tasks, setTasks] = useState<PaperTask[]>(primaryDocument.tasks);
  const stats = getTaskStats(primaryDocument);
  const requirements = getRequirementStats(primaryDocument);
  const daysRemaining = getDaysRemaining(primaryDocument.deadline);
  const toggleTask = (id: string) => setTasks((current) => current.map((task) => task.id === id ? { ...task, status: task.status === "completed" ? "open" : "completed" } : task));
  const liveStats = { ...stats, completed: tasks.filter((task) => task.status === "completed").length, open: tasks.filter((task) => task.status === "open").length };

  return <div className="app-page-enter space-y-8">
    <SectionTitle eyebrow={mockToday} title="Here’s what needs your attention today." copy="Stay ahead of deadlines and keep your paperwork moving." action={<PrimaryButton href="/upload"><Upload aria-hidden="true" className="size-4" />Upload document</PrimaryButton>} />

    <section aria-labelledby="priority-title" className="relative overflow-hidden rounded-[17px] bg-[#f2f5fa] p-5 shadow-[inset_0_0_0_1px_rgba(37,99,235,.1)] sm:p-7"><div aria-hidden="true" className="absolute right-0 top-0 h-full w-1/3 bg-[radial-gradient(ellipse_at_top_right,rgba(91,129,245,.14),transparent_68%)]" /><div className="relative flex flex-col gap-6 lg:flex-row lg:items-center lg:justify-between"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><span className="text-[10px] font-semibold uppercase tracking-[.14em] text-[#5c6e91]">Highest priority</span><StatusBadge status="action_required" /></div><h2 id="priority-title" className="text-balance mt-3 text-xl font-semibold tracking-[-.035em] text-[#263752] sm:text-2xl">{primaryDocument.title}</h2><div className="mt-4 flex flex-wrap items-center gap-x-4 gap-y-2 text-xs text-[#6f7d94]"><span className="font-semibold text-[#9d6a1d]">Due {primaryDocument.deadlineLabel?.replace("Due ", "")}</span><span>{daysRemaining} days remaining</span><span>{liveStats.open} tasks remaining</span></div><p className="mt-4 flex items-center gap-2 text-sm text-[#687790]"><AlertCircle aria-hidden="true" className="size-4 shrink-0 text-[#b27b28]" />{requirements.missing} required documents are still missing.</p></div><div className="relative flex shrink-0 flex-col gap-2 sm:flex-row lg:flex-col xl:flex-row"><PrimaryButton href={`/documents/${primaryDocument.id}`}>Continue application <ArrowRight aria-hidden="true" className="size-4" /></PrimaryButton><Link href={`/documents/${primaryDocument.id}`} className="inline-flex min-h-10 items-center justify-center rounded-[9px] px-3 text-xs font-semibold text-[#48628f] transition-[background-color,color] duration-150 ease-out hover:bg-white hover:text-[#315fca]">View document</Link></div></div></section>

    <section aria-labelledby="next-up-title"><div className="flex items-end justify-between gap-3"><div><h2 id="next-up-title" className="text-base font-semibold text-[#293a57]">Next up</h2><p className="mt-1 text-xs text-[#7b8799]">Your nearest deadlines.</p></div><Link href="/deadlines" className="inline-flex min-h-10 items-center gap-1 px-2 text-xs font-semibold text-[#3c66c1] hover:text-[#245eea]">View deadlines <ArrowRight aria-hidden="true" className="size-3.5" /></Link></div><div className="mt-4 grid gap-2.5 lg:grid-cols-3">{upcomingDeadlines.map((deadline) => <DeadlineRow key={deadline.documentId} {...deadline} />)}</div></section>

    <section aria-labelledby="insight-title" className="rounded-[15px] bg-[#eaf1ff] p-5 shadow-[inset_0_0_0_1px_rgba(37,99,235,.08)] sm:p-6"><div className="flex items-start gap-3"><span className="flex size-9 shrink-0 items-center justify-center rounded-[9px] bg-white text-[#416dcc]"><Sparkles aria-hidden="true" className="size-4" /></span><div><h2 id="insight-title" className="text-sm font-semibold text-[#30466f]">PaperPilot Insight</h2><p className="text-pretty mt-2 text-sm leading-6 text-[#5e6e8a]">Your scholarship application has the nearest deadline and {requirements.missing} missing requirements. Preparing your transcript and recommendation letter should be your next priority.</p><Link href={`/documents/${primaryDocument.id}?tab=tasks`} className="mt-3 inline-flex min-h-10 items-center gap-1 text-xs font-semibold text-[#315fca] hover:text-[#204da9]">Review checklist <ArrowRight aria-hidden="true" className="size-3.5" /></Link></div></div></section>

    <section aria-labelledby="workspace-title"><div><h2 id="workspace-title" className="text-base font-semibold text-[#293a57]">Your workspace</h2><p className="mt-1 text-xs text-[#7b8799]">A compact view of what is moving.</p></div><div className="mt-4 grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><MetricCard label="Documents" value={String(documents.length)} detail="Across your Paper Inbox" icon={FileText} /><MetricCard label="Open tasks" value={String(openTasks.length)} detail="Across all documents" icon={ListTodo} tone="green" /><MetricCard label="Upcoming deadlines" value={String(upcomingDeadlines.length)} detail="Within the next 7 days" icon={CalendarClock} tone="amber" /><MetricCard label="Need attention" value={String(documents.filter((document) => document.status === "action_required" || document.status === "needs_attention").length)} detail="Review soon" icon={AlertCircle} tone="red" /></div></section>

    <div className="grid gap-6 xl:grid-cols-[minmax(0,1.35fr)_minmax(300px,.8fr)]"><section aria-labelledby="recent-title" className="rounded-[16px] bg-[#f0f4fa] p-4 sm:p-5"><div className="flex items-center justify-between gap-3"><div><h2 id="recent-title" className="text-base font-semibold text-[#293a57]">Recent documents</h2><p className="mt-1 text-xs text-[#7b8799]">Progress from your latest paperwork.</p></div><Link href="/inbox" className="inline-flex min-h-10 items-center gap-1 px-2 text-xs font-semibold text-[#3c66c1] hover:text-[#245eea]">Open Inbox <ArrowRight aria-hidden="true" className="size-3.5" /></Link></div><div className="mt-5 space-y-2.5">{documents.slice(0, 4).map((document) => <DocumentRow key={document.id} document={document} />)}</div></section><section aria-labelledby="tasks-title" className="rounded-[16px] bg-white p-5 shadow-[0_0_0_1px_rgba(15,23,42,.065)]"><div className="flex items-center justify-between"><div><h2 id="tasks-title" className="text-base font-semibold text-[#293a57]">Tasks that need your attention</h2><p className="mt-1 text-xs text-[#7b8799]">{liveStats.open} open scholarship tasks</p></div><CheckSquare aria-hidden="true" className="size-4 text-[#5c78bc]" /></div><div className="mt-5 divide-y divide-[#edf0f4]">{tasks.map((task) => <label key={task.id} className="flex cursor-pointer items-start gap-3 py-3 first:pt-0 last:pb-0"><input type="checkbox" checked={task.status === "completed"} onChange={() => toggleTask(task.id)} className="sr-only" /><TaskStatusIcon completed={task.status === "completed"} /><span className="min-w-0"><span className={`block text-sm font-medium ${task.status === "completed" ? "text-[#8b95a4] line-through" : "text-[#3a4964]"}`}>{task.title}</span><span className="mt-1 block text-[11px] text-[#8a95a4]">{task.due} · {primaryDocument.title}</span></span></label>)}</div><Link href="/tasks" className="mt-4 inline-flex min-h-10 items-center gap-1 text-xs font-semibold text-[#315fca] hover:text-[#204da9]">View all tasks <ArrowRight aria-hidden="true" className="size-3.5" /></Link></section></div>
  </div>;
}
