import Link from "next/link";
import { CalendarClock, ChevronRight } from "lucide-react";
import { documents, getTaskStats } from "@/lib/mock-data";
import { SectionTitle, StatusBadge } from "./ui";

export function DeadlinesPage() {
  const datedDocuments = documents.filter((document) => document.deadline);
  const groups = [{ label: "Today", items: [] }, { label: "This week", items: datedDocuments.slice(0, 1) }, { label: "Upcoming", items: datedDocuments.slice(1) }];
  return <div className="app-page-enter space-y-8"><SectionTitle eyebrow="Across your paperwork" title="Deadlines" copy="Important dates from across your paperwork." /><div className="space-y-8">{groups.map((group) => <section key={group.label}><div className="flex items-center gap-3"><span className="flex size-8 items-center justify-center rounded-[9px] bg-[#edf3ff] text-[#416dcc]"><CalendarClock aria-hidden="true" className="size-4" /></span><h2 className="text-sm font-semibold text-[#34445f]">{group.label}</h2><span className="h-px flex-1 bg-[#e2e7ef]" /></div>{group.items.length ? <div className="mt-3 space-y-2.5">{group.items.map((document) => { const stats = getTaskStats(document); return <Link key={document.id} href={`/documents/${document.id}`} className="group flex flex-col gap-3 rounded-[13px] bg-white p-4 shadow-[0_0_0_1px_rgba(15,23,42,.065)] transition-[transform,box-shadow,background-color] duration-150 ease-out hover:-translate-y-px hover:bg-[#fcfdff] hover:shadow-[0_0_0_1px_rgba(37,99,235,.14)] sm:flex-row sm:items-center"><span className="w-20 shrink-0 text-sm font-semibold text-[#3f5f9d]">{document.deadlineLabel?.replace("Due ", "")}</span><span className="min-w-0 flex-1"><span className="block truncate text-sm font-semibold text-[#34435f] group-hover:text-[#245eea]">{document.title}</span><span className="mt-1 block text-[11px] text-[#8993a4]">{stats.open} {stats.open === 1 ? "task" : "tasks"} remaining</span></span><StatusBadge status={document.status} /><ChevronRight aria-hidden="true" className="hidden size-4 text-[#9aa5b4] sm:block" /></Link>; })}</div> : <p className="mt-3 rounded-[12px] bg-[#f0f4fa] px-4 py-3 text-xs text-[#8490a2]">No urgent dates today.</p>}</section>)}</div></div>;
}
