"use client";

import { useMemo, useState } from "react";
import { AlertTriangle, FileText, MoreHorizontal, Paperclip, Sparkles } from "lucide-react";
import type { PaperDocument, PaperTask } from "@/lib/mock-data";
import { DeadlineIcon, SecondaryButton, StatusBadge, TaskStatusIcon } from "./ui";

export function DocumentDetail({ document }: { document: PaperDocument }) {
  const [activeTab, setActiveTab] = useState<"overview" | "checklist" | "original">("overview");
  const [tasks, setTasks] = useState<PaperTask[]>(document.tasks);
  const [toast, setToast] = useState("");
  const completedCount = useMemo(() => tasks.filter((task) => task.status === "completed").length, [tasks]);
  const toggleTask = (id: string) => setTasks((current) => current.map((task) => task.id === id ? { ...task, status: task.status === "completed" ? "open" : "completed" } : task));
  const showToast = (message: string) => { setToast(message); window.setTimeout(() => setToast(""), 2400); };

  return <div className="app-page-enter space-y-7"><header className="flex flex-col gap-5 border-b border-[#e2e7ef] pb-6 lg:flex-row lg:items-start lg:justify-between"><div className="flex min-w-0 items-start gap-3"><span className="flex size-11 shrink-0 items-center justify-center rounded-[11px] bg-[#edf3ff] text-[#416dcc]"><FileText aria-hidden="true" className="size-5" /></span><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><span className="text-[10px] font-semibold uppercase tracking-[.12em] text-[#6e7d97]">{document.type}</span><StatusBadge status={document.status} /></div><h1 className="text-balance mt-2 text-[clamp(1.7rem,4vw,2.5rem)] font-semibold leading-[1.06] tracking-[-.05em] text-[#1b2943]">{document.title}</h1><p className="mt-3 flex flex-wrap items-center gap-2 text-xs text-[#8993a3]"><span>Uploaded {document.uploadedAt}</span><span aria-hidden="true">·</span><span>{document.fileName}</span><span aria-hidden="true">·</span><span>{document.fileSize}</span></p></div></div><div className="flex items-center gap-2 lg:pt-1"><SecondaryButton onClick={() => showToast("Original document preview is coming next.")}><Paperclip aria-hidden="true" className="size-4" />View original</SecondaryButton><button type="button" aria-label="More document actions" onClick={() => showToast("More document actions are coming next.")} className="flex size-11 items-center justify-center rounded-[10px] bg-white text-[#657187] shadow-[0_0_0_1px_rgba(15,23,42,.1)] transition-[background-color,transform] duration-150 ease-out hover:bg-[#f1f4f8] active:scale-[0.96]"><MoreHorizontal aria-hidden="true" className="size-4" /></button></div></header>

    <div role="tablist" aria-label="Document views" className="flex gap-1 border-b border-[#e2e7ef]"><button type="button" role="tab" aria-selected={activeTab === "overview"} onClick={() => setActiveTab("overview")} className={`min-h-11 rounded-t-[9px] px-3 text-xs font-semibold transition-[background-color,color] duration-150 ease-out ${activeTab === "overview" ? "border-b-2 border-[#3567d2] text-[#315fca]" : "text-[#7c8798] hover:bg-[#f1f4f8]"}`}>Overview</button><button type="button" role="tab" aria-selected={activeTab === "checklist"} onClick={() => setActiveTab("checklist")} className={`min-h-11 rounded-t-[9px] px-3 text-xs font-semibold transition-[background-color,color] duration-150 ease-out ${activeTab === "checklist" ? "border-b-2 border-[#3567d2] text-[#315fca]" : "text-[#7c8798] hover:bg-[#f1f4f8]"}`}>Checklist</button><button type="button" role="tab" aria-selected={activeTab === "original"} onClick={() => setActiveTab("original")} className={`min-h-11 rounded-t-[9px] px-3 text-xs font-semibold transition-[background-color,color] duration-150 ease-out ${activeTab === "original" ? "border-b-2 border-[#3567d2] text-[#315fca]" : "text-[#7c8798] hover:bg-[#f1f4f8]"}`}>Original document</button></div>

    {activeTab === "original" ? <section role="tabpanel" className="rounded-[16px] bg-white p-8 text-center shadow-[0_0_0_1px_rgba(15,23,42,.065)] sm:p-16"><span className="mx-auto flex size-12 items-center justify-center rounded-[12px] bg-[#f0f3f7] text-[#8290a4]"><FileText aria-hidden="true" className="size-5" /></span><h2 className="mt-5 text-lg font-semibold text-[#30415e]">PDF preview unavailable in prototype.</h2><p className="mt-2 text-sm text-[#8490a2]">{document.fileName} will be viewable here when document processing is connected.</p></section> : <div className="grid gap-6 lg:grid-cols-[minmax(0,1.65fr)_minmax(270px,.8fr)]"><main className="space-y-6">
      {activeTab === "overview" && <><section className="rounded-[16px] bg-white p-5 shadow-[0_0_0_1px_rgba(15,23,42,.065)] sm:p-6"><h2 className="text-base font-semibold text-[#2b3b57]">What is this?</h2><p className="text-pretty mt-4 max-w-3xl text-sm leading-7 text-[#65728a]">{document.summary}</p></section><section className="rounded-[16px] bg-[#fffaf0] p-5 shadow-[inset_0_0_0_1px_rgba(218,164,75,.14)] sm:p-6"><div className="flex items-start justify-between gap-4"><div><p className="text-[10px] font-semibold uppercase tracking-[.13em] text-[#9c752c]">Important deadline</p><p className="tabular-nums mt-3 text-2xl font-semibold tracking-[-.04em] text-[#624c26]">{document.deadline ?? "No deadline"}</p><p className="mt-1 text-xs text-[#9a8154]">9 days remaining</p></div><span className="flex items-center gap-1.5 rounded-full bg-[#fff0d2] px-2.5 py-1 text-[10px] font-semibold text-[#9c6b20]"><AlertTriangle aria-hidden="true" className="size-3.5" />Priority High</span></div></section></>}
      <section role="tabpanel" className="rounded-[16px] bg-white p-5 shadow-[0_0_0_1px_rgba(15,23,42,.065)] sm:p-6"><div className="flex items-center justify-between gap-3"><div><h2 className="text-base font-semibold text-[#2b3b57]">{activeTab === "checklist" ? "Checklist" : "Next actions"}</h2><p className="mt-1 text-xs text-[#8590a2]">{completedCount} of {tasks.length} completed</p></div><span className="text-xs font-semibold text-[#72809a]">{Math.round((completedCount / tasks.length) * 100)}%</span></div><div className="mt-5 h-1.5 overflow-hidden rounded-full bg-[#edf1f6]"><div className="h-full rounded-full bg-[#5a7fdc] transition-[width] duration-200 ease-out" style={{ width: `${(completedCount / tasks.length) * 100}%` }} /></div><div className="mt-4 divide-y divide-[#edf0f4]">{tasks.map((task) => <label key={task.id} className="flex cursor-pointer items-start gap-3 py-3 first:pt-0 last:pb-0"><input type="checkbox" className="sr-only" checked={task.status === "completed"} onChange={() => toggleTask(task.id)} /><TaskStatusIcon completed={task.status === "completed"} /><span className="min-w-0"><span className={`block text-sm font-medium ${task.status === "completed" ? "text-[#8b95a4] line-through" : "text-[#3a4964]"}`}>{task.title}</span><span className="mt-1 flex items-center gap-1 text-[11px] text-[#8a95a4]"><DeadlineIcon />{task.due}</span></span></label>)}</div></section>
      {activeTab === "overview" && <section className="rounded-[16px] bg-[#eef4ff] p-5 shadow-[inset_0_0_0_1px_rgba(37,99,235,.08)] sm:p-6"><div className="flex items-center gap-2 text-[#416dcc]"><Sparkles aria-hidden="true" className="size-4" /><h2 className="text-sm font-semibold">Why this matters</h2></div><p className="text-pretty mt-4 text-sm leading-6 text-[#62728f]">The application must be submitted before July 28. Two required documents are still missing, so preparing those should be your next priority.</p></section>}
    </main><aside className="space-y-4"><section className="rounded-[16px] bg-white p-5 shadow-[0_0_0_1px_rgba(15,23,42,.065)]"><h2 className="text-sm font-semibold text-[#2b3b57]">Document overview</h2><dl className="mt-5 space-y-4">{[["Document type", document.type], ["Deadline", document.deadline ?? "None"], ["Urgency", "High"], ["Required documents", String(document.requiredDocuments.length)], ["Open tasks", String(tasks.filter((task) => task.status === "open").length)]].map(([term, value]) => <div key={term} className="flex items-center justify-between gap-3 text-xs"><dt className="text-[#8993a3]">{term}</dt><dd className="text-right font-semibold text-[#42516b]">{value}</dd></div>)}</dl></section><section className="rounded-[16px] bg-[#f0f4fa] p-5"><p className="text-[10px] font-semibold uppercase tracking-[.13em] text-[#5a73b6]">PaperPilot suggests</p><p className="text-pretty mt-3 text-sm font-semibold leading-6 text-[#344968]">Your academic transcript and recommendation letter are still missing.</p><p className="mt-3 text-xs leading-5 text-[#7d899c]">Recommended next step: prepare missing documents.</p><div className="mt-5 grid gap-2"><SecondaryButton onClick={() => showToast("Reminders are coming in the next PaperPilot version.")} className="w-full">Create reminder</SecondaryButton><SecondaryButton onClick={() => showToast("Reply generation is coming in the next PaperPilot version.")} className="w-full">Generate reply</SecondaryButton></div></section></aside></div>}
    {toast && <div role="status" className="fixed bottom-5 left-1/2 z-[70] -translate-x-1/2 rounded-[10px] bg-[#17243e] px-4 py-3 text-xs font-medium text-white shadow-[0_14px_35px_-18px_rgba(15,23,42,.65)]">{toast}</div>}
  </div>;
}
