"use client";

import { Bot, Globe2, Send, Settings, Sparkles } from "lucide-react";
import { useTranslations } from "next-intl";
import { LanguageSwitcher } from "@/components/language-switcher";

export function CopilotPage() {
  const t = useTranslations("Copilot");
  const suggestions = t.raw("suggestions") as string[];
  return <div className="app-page-enter mx-auto max-w-3xl space-y-7"><header><p className="text-[10px] font-semibold uppercase tracking-[.16em] text-[#4e70c7]">{t("eyebrow")}</p><h1 className="text-balance mt-2 text-[clamp(1.9rem,4vw,2.7rem)] font-semibold tracking-[-.05em] text-[#1b2943]">{t("title")}</h1><p className="text-pretty mt-3 max-w-2xl text-sm leading-6 text-[#707b8e]">{t("copy")}</p></header><section className="overflow-hidden rounded-[18px] bg-white shadow-[0_0_0_1px_rgba(15,23,42,.065),0_18px_45px_-35px_rgba(15,23,42,.25)]"><div className="flex items-center justify-between gap-3 border-b border-[#e7ebf1] px-4 py-3 sm:px-5"><div className="flex min-w-0 items-center gap-3"><span className="flex size-9 shrink-0 items-center justify-center rounded-[9px] bg-[#eaf1ff] text-[#416dcc]"><Bot aria-hidden="true" className="size-4" /></span><span className="min-w-0"><span className="block text-xs font-semibold text-[#30405c]">PaperPilot Copilot</span><span className="mt-0.5 block truncate text-[10px] text-[#8993a4]">{t("connected")}</span></span></div><span className="inline-flex shrink-0 items-center gap-1.5 rounded-full bg-[#eaf7ef] px-2.5 py-1 text-[10px] font-semibold text-[#347c50]"><span aria-hidden="true" className="size-1.5 rounded-full bg-current" />{t("ready")}</span></div><div className="min-h-[290px] bg-[#f7f9fc] p-5 sm:p-8"><div className="mx-auto max-w-xl"><span className="flex size-10 items-center justify-center rounded-[10px] bg-white text-[#416dcc] shadow-[0_0_0_1px_rgba(15,23,42,.065)]"><Sparkles aria-hidden="true" className="size-4" /></span><p className="text-pretty mt-4 text-sm leading-6 text-[#6b7890]">{t("prototype")}</p><div className="mt-6 grid gap-2 sm:grid-cols-3">{suggestions.map((question) => <button key={question} type="button" className="min-h-11 rounded-[10px] bg-white px-3 py-2 text-left text-xs font-medium leading-5 text-[#4a5d7b] shadow-[0_0_0_1px_rgba(15,23,42,.065)] transition-[background-color,transform] duration-150 ease-out hover:bg-[#edf3ff] active:scale-[0.96]">{question}</button>)}</div></div></div><div className="border-t border-[#e7ebf1] p-3 sm:p-4"><div className="mx-auto flex max-w-xl items-center gap-2 rounded-[11px] bg-[#f7f8fa] p-1.5 pl-4 shadow-[inset_0_0_0_1px_rgba(15,23,42,.08)]"><span className="min-w-0 flex-1 truncate text-xs text-[#9299a4]">{t("prompt")}</span><button type="button" aria-label={t("title")} className="flex size-9 shrink-0 items-center justify-center rounded-[9px] bg-[#245eea] text-white transition-transform duration-150 ease-out active:scale-[0.96]"><Send aria-hidden="true" className="size-4" /></button></div></div></section></div>;
}

export function SettingsPage() {
  const t = useTranslations("Settings");
  return <div className="app-page-enter mx-auto max-w-3xl space-y-7"><header><p className="text-[10px] font-semibold uppercase tracking-[.16em] text-[#4e70c7]">{t("eyebrow")}</p><h1 className="text-balance mt-2 text-[clamp(1.9rem,4vw,2.7rem)] font-semibold tracking-[-.05em] text-[#1b2943]">{t("title")}</h1><p className="text-pretty mt-3 max-w-2xl text-sm leading-6 text-[#707b8e]">{t("copy")}</p></header><section className="rounded-[18px] bg-white p-5 shadow-[0_0_0_1px_rgba(15,23,42,.065)] sm:p-7"><div className="flex items-start gap-3"><span className="flex size-10 shrink-0 items-center justify-center rounded-[10px] bg-[#eaf1ff] text-[#416dcc]"><Globe2 aria-hidden="true" className="size-4" /></span><div><h2 className="text-base font-semibold text-[#2b3b57]">{t("languageRegion")}</h2><p className="text-pretty mt-2 text-sm leading-6 text-[#788497]">{t("languageCopy")}</p></div></div><div className="mt-6 flex flex-col gap-3 rounded-[13px] bg-[#f5f7fa] p-4 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-xs font-semibold text-[#3a4964]">{t("preferredLanguage")}</p><p className="mt-1 text-[11px] text-[#8792a4]">{t("english")} · {t("indonesian")}</p></div><LanguageSwitcher /></div></section><div className="flex items-center gap-3 rounded-[14px] bg-[#f0f4fa] p-4 text-xs leading-5 text-[#758195]"><Settings aria-hidden="true" className="size-4 shrink-0 text-[#5e79bd]" /><span>PaperPilot</span></div></div>;
}
